FROM python:3.12-alpine AS builder
WORKDIR /app
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt --target=/app/deps
COPY manage.py .
COPY initial_setup.py .
COPY jenkins_project ./jenkins_project
COPY myapp ./myapp

FROM gcr.io/distroless/python3:nonroot
WORKDIR /app
ENV PYTHONPATH=/app/deps
ENV PYTHONUNBUFFERED=1
COPY --from=builder /app /app
EXPOSE 8000
CMD [ "initial_setup.py" ]