FROM python:3.9-slim

ENV PYTHONUNBUFFERED 1

# Set the working directory inside the container
WORKDIR /app

# Copy requirements.txt to the working directory
COPY requirements.txt ./

# Install application dependencies
RUN pip install --no-cache-dir -r requirements.txt  

# Copy the rest of the application code
COPY . .    
# Expose the port the app runs on
EXPOSE 8000 

# Command to run the application
CMD [ "python", "manage.py", "runserver", "0.0.0.0:8000" ]