pipeline {
    agent { label 'my_server'}

    environment {
        DOCKER_IMAGE = "django-demo-app:${env.BUILD_NUMBER}"
        CONTAINER_NAME = "django-demo-container"
    }

    stages {
        stage('Checkout Code') {
            steps {
                checkout scmGit(branches: [[name: '*/master']], extensions: [], userRemoteConfigs: [[credentialsId: 'github', url: 'https://github.com/aabhinnav1999/jenkins_github']])
            }
        }

        stage('Build Docker Image') {
            steps {
                echo "--- Building Docker image ---"
                script {
                    sh ''' cd django_app
                    docker build -t ${DOCKER_IMAGE} .
                    '''
                }
                echo "Docker image ${DOCKER_IMAGE} built successfully."
            }
        }

        stage('Login to Docker Hub') {
            steps {
                echo "--- Logging in to Docker Hub ---"
                script {
                    withCredentials([usernamePassword(credentialsId: 'dockerhub-credentials', passwordVariable: 'DOCKER_PASSWORD', usernameVariable: 'DOCKER_USERNAME')]) {
                        sh 'echo \"$DOCKER_PASSWORD\" | docker login -u \"$DOCKER_USERNAME\" --password-stdin'
                    }
                }
                echo "Logged in to Docker Hub."
            }
        }

    }
}