pipeline {
    agent { label 'my_server'}

    environment {
        DOCKER_IMAGE = "jenkins_django:${env.BUILD_NUMBER}"
        DOCKER_USERNAME = "aabhinnavdocker" // Replace with your Docker Hub username
    }

    stages {
        stage('1.Checkout Code') {
            steps {
                checkout scmGit(branches: [[name: '*/master']], extensions: [], userRemoteConfigs: [[url: 'https://github.com/aabhinnav1999/jenkins_github.git']])
            }
        }

        stage('2.Build Docker Image') {
            steps {
                echo "--- Building Docker image ---"
                script {
                    sh ''' cd django_app
                    docker build -t ${DOCKER_IMAGE} .
                    '''
                }
                echo "Docker image ${DOCKER_IMAGE} built successfully."
            }
        }

        stage('3.Login to Docker Hub') {
            steps {
                echo "--- Logging in to Docker Hub ---"
                script {
                    withCredentials([usernamePassword(credentialsId: 'dockerhub-credentials', passwordVariable: 'DOCKER_PASSWORD', usernameVariable: 'DOCKER_USERNAME')]) {
                        sh 'echo \"$DOCKER_PASSWORD\" | docker login -u \"$DOCKER_USERNAME\" --password-stdin'
                    }
                }
                echo "Logged in to Docker Hub."
            }
        }

        stage('4. Docker Scout Scan') {
            steps {
                echo "--- Running Docker Scout scan for HIGH and CRITICAL vulnerabilities ---"
                script {
                    sh "docker scout cves ${DOCKER_IMAGE}"
                }
            }
        }

        stage('5. Tag and Push Docker Image to Docker Hub') {
            steps {
                echo "--- Tagging the Docker image ---"
                script {
                    sh "docker image tag ${DOCKER_IMAGE} ${DOCKER_USERNAME}/${DOCKER_IMAGE}"
                }

                echo "--- Pushing Docker image to Docker Hub ---"
                script {
                    sh "docker image push ${DOCKER_USERNAME}/${DOCKER_IMAGE}"
                }
                echo "Docker image ${DOCKER_IMAGE} pushed to Docker Hub."
            }
        }
    }
}