pipeline {
    // Specifies where the pipeline will run. 'any' means it can run on any available agent.
    agent {label 'my_server'}

    // Define environment variables that will be available throughout the pipeline
    environment {
        // Defines the Docker image name and tags it with the Jenkins build number
        DOCKER_IMAGE = "jenkins_node:${env.BUILD_NUMBER}"
        DOCKER_USERNAME = "aabhinnavdocker" // Replace with your Docker Hub username
    }

    // Define the stages of your CI/CD pipeline
    stages {
        stage('1.Checkout Code') {
            steps {
                echo "--- Checking out code from GitHub ---"
                // Clones the Git repository.
                // 'branch': Specifies the branch to clone (e.g., 'main' or 'master')
                // 'credentialsId': ID of the credentials configured in Jenkins for GitHub access
                // 'url': The URL of your GitHub repository
                checkout scmGit(branches: [[name: '*/master']], extensions: [], userRemoteConfigs: [[url: 'https://github.com/aabhinnav1999/jenkins_github.git']])
                echo "Code checked out successfully."
            }
        }

        stage('2.Build Docker Image') {
            steps {
                echo "--- Building Docker image ---"
                script {
                    // Executes a shell command to build the Docker image
                    // '-t' tags the image with the defined DOCKER_IMAGE name
                    // '.' specifies the Dockerfile is in the current directory
                    sh ''' cd node_app
                    docker build -t ${DOCKER_IMAGE} .
                    '''
                }
                echo "Docker image ${DOCKER_IMAGE} built successfully."
            }
        }

        stage('3.Login to Docker Hub') {
            steps {
                echo "--- Logging in to Docker Hub ---"
                script {
                    // Uses the 'withCredentials' binding to securely access Docker Hub credentials
                    // 'dockerhub-credentials' must be a 'Username with password' type credential in Jenkins
                    withCredentials([usernamePassword(credentialsId: 'dockerhub-credentials', passwordVariable: 'DOCKER_PASSWORD', usernameVariable: 'DOCKER_USERNAME')]) {
                        sh 'echo \"$DOCKER_PASSWORD\" | docker login -u \"$DOCKER_USERNAME\" --password-stdin'
                    }
                }
                echo "Logged in to Docker Hub."
            }
        }

        stage('4.Tag and Push Docker Image to Docker Hub') {
            steps {
                echo "--- Tagging the Docker image ---"
                script {
                    sh "docker image tag ${DOCKER_IMAGE} ${DOCKER_USERNAME}/${DOCKER_IMAGE}"
                }

                echo "--- Pushing Docker image to Docker Hub ---"
                script {
                    // Pushes the built image to Docker Hub
                    sh "docker image push ${DOCKER_USERNAME}/${DOCKER_IMAGE}"
                }
                echo "Docker image ${DOCKER_IMAGE} pushed to Docker Hub."
            }
        }  
    }

    post {
        success {
            echo "Pipeline completed successfully."
        }
        failure {
            echo "Pipeline failed. Image was not pushed because build/scan did not pass."
        }
        always {
            echo "--- Cleaning up local images ---"
            sh """docker image rm -f ${DOCKER_IMAGE} || true 
            docker image rm -f ${DOCKER_USERNAME}/${DOCKER_IMAGE} || true"""
        }
    }

}